<a href="https://colab.research.google.com/github/janewen134/tensorflow_self_improvement/blob/after_class_revision/revision1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

a = tf.constant(np.arange(1,9), dtype=tf.int32)
print(a)

tf.Tensor([1 2 3 4 5 6 7 8], shape=(8,), dtype=int32)


In [16]:
import tensorflow as tf
import numpy as np
a = np.arange(1,3, dtype=np.int32)
b = tf.convert_to_tensor(a)
print(a)

[1 2]


In [7]:
import tensorflow as tf
tf.ones([3,3,3])
tf.zeros([6,7],dtype=tf.int16)
c=tf.fill([3,3,3,3], 0)
print(c)

tf.Tensor(
[[[[0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]]]


 [[[0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]]]


 [[[0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]]]], shape=(3, 3, 3, 3), dtype=int32)
