<a href="https://colab.research.google.com/github/janewen134/tensorflow_self_improvement/blob/after_class_revision/revision1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

a = tf.constant(np.arange(1,9), dtype=tf.int32)
print(a)

tf.Tensor([1 2 3 4 5 6 7 8], shape=(8,), dtype=int32)


In [ ]:
import tensorflow as tf
import numpy as np
a = np.arange(1,3, dtype=np.int32)
b = tf.convert_to_tensor(a)
print(a)

[1 2]


In [ ]:
import tensorflow as tf
a = tf.random.normal([5,5,5], mean=0, stddev=2)
b = tf.random.truncated_normal([5,5,5], mean=0, stddev=2)
c = tf.random.uniform([3,3], minval=-2, maxval=2)
print(c)

tf.Tensor(
[[-0.8926854  -1.7232256   1.246427  ]
 [-1.6731582   1.941864    1.4627423 ]
 [ 0.5046272   0.6454396   0.72279024]], shape=(3, 3), dtype=float32)


In [ ]:
import tensorflow as tf
tf.ones([3,3,3])
tf.zeros([6,7],dtype=tf.int16)
c=tf.fill([3,3,3,3], 0)
#print(c)

In [ ]:
x1 = tf.constant ([1., 2., 3.], dtype=tf.float64)
print(x1)
x2 = tf.cast (x1, tf.int32)
print(x2)
print (tf.reduce_min(x2), tf.reduce_max(x2))

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float64)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32) tf.Tensor(3, shape=(), dtype=int32)


In [ ]:
x=tf.constant( [ [ 1, 2, 3],
[ 2,2,3]])
print(x)
print(tf.reduce_mean( x )) 
print(tf.reduce_sum( x, axis=1 ))

tf.Tensor(
[[1 2 3]
 [2 2 3]], shape=(2, 3), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor([6 7], shape=(2,), dtype=int32)


In [ ]:
w = tf.Variable(tf.random.normal([2, 2], mean=0, stddev=1))

In [ ]:
a = tf.ones([1, 3])
b = tf.fill([1, 3], 3.) 
print(a)
print(b)
print(tf.add(a,b)) 
print(tf.subtract(a,b)) 
print(tf.multiply(a,b)) 
print(tf.divide(b,a))

tf.Tensor([[1. 1. 1.]], shape=(1, 3), dtype=float32)
tf.Tensor([[3. 3. 3.]], shape=(1, 3), dtype=float32)
tf.Tensor([[4. 4. 4.]], shape=(1, 3), dtype=float32)
tf.Tensor([[-2. -2. -2.]], shape=(1, 3), dtype=float32)
tf.Tensor([[3. 3. 3.]], shape=(1, 3), dtype=float32)
tf.Tensor([[3. 3. 3.]], shape=(1, 3), dtype=float32)


In [ ]:
a = tf.fill([2, ], 3.) 
print(a) 
print(tf.pow(a, 3)) 
print(tf.square(a)) 
print(tf.sqrt(a))
b = tf.fill([1, 2], 3.) 
print(b) 
print(tf.square(b))
print(tf.pow(b,3))
print(tf.sqrt(b))

tf.Tensor([3. 3.], shape=(2,), dtype=float32)
tf.Tensor([27. 27.], shape=(2,), dtype=float32)
tf.Tensor([9. 9.], shape=(2,), dtype=float32)
tf.Tensor([1.7320508 1.7320508], shape=(2,), dtype=float32)
tf.Tensor([[3. 3.]], shape=(1, 2), dtype=float32)
tf.Tensor([[9. 9.]], shape=(1, 2), dtype=float32)
tf.Tensor([[27. 27.]], shape=(1, 2), dtype=float32)
tf.Tensor([[1.7320508 1.7320508]], shape=(1, 2), dtype=float32)


In [ ]:
a = tf.ones([3, 2])
b = tf.fill([2, 3], 3.) 
print(tf.matmul(a,b))

tf.Tensor(
[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]], shape=(3, 3), dtype=float32)


In [ ]:
import tensorflow as tf

features = tf.ones([5, 4])
labels = tf.constant([12,22,44,21])
dataset = tf.data.Dataset.from_tensor_slices((features[:,:1], features[:,1:]))
print(dataset)
for element in dataset:
  print(element)

<TensorSliceDataset shapes: ((1,), (3,)), types: (tf.float32, tf.float32)>
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>, <tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>, <tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>, <tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>, <tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>, <tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>)


In [ ]:
with tf.GradientTape() as tape:
  # w = tf.Variable(tf.constant(3.0))
  # loss = tf.pow(w,2) 
  w = tf.Variable(3.0)
  loss = tf.square(w) 
grad = tape.gradient(loss, w)
print(grad)

tf.Tensor(6.0, shape=(), dtype=float32)


In [ ]:
seq = ['one', 'two', 'three']
i = 9
for j, element in enumerate(seq): 
  print(i, element)
  print(j, element)

9 one
0 one
9 two
1 two
9 three
2 three


In [ ]:
classes = 4
labels = tf.constant([1,2,5]) # max value 5 is out of range
labels = tf.constant([1,2,4]) # max value is 4 at a maximum
labels = tf.constant([-1, 0, 4]) # min value -1 is out of range, too
output = tf.one_hot(labels, depth=classes)
print(output)

tf.Tensor(
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)


In [1]:
import tensorflow as tf

t = tf.nn.softmax([2.,3.,1.])
print(t)

t_ = tf.constant([2.,3,1])
t__ = tf.nn.softmax(t_)
print(t__)
# They are definitely the same thing!!!!!

tf.Tensor([0.24472848 0.66524094 0.09003057], shape=(3,), dtype=float32)
tf.Tensor([0.24472848 0.66524094 0.09003057], shape=(3,), dtype=float32)


In [ ]:
y = tf.constant([1., 2, -8]) # The value should be half, bfloat16, float, double
y_pro = tf.nn.softmax(y)
print("After softmax, y_pro is: ", y_pro)

After softmax, y_pro is:  tf.Tensor([2.6893252e-01 7.3103434e-01 3.3188910e-05], shape=(3,), dtype=float32)


In [ ]:
w = tf.Variable(3)
w.assign_sub(1)
print(w)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2>


In [ ]:
import numpy as np
test = np.array([[1, 2, 3], [2, 3, 4], [5, 4, 3], [8, 7, 2]])
print(test)
print( tf.argmax (test, axis=0)) # 返回每一列(经度)最大值的索引 
print( tf.argmax (test, axis=1)) # 返回每一行(纬度)最大值的索引

[[1 2 3]
 [2 3 4]
 [5 4 3]
 [8 7 2]]
tf.Tensor([3 3 1], shape=(3,), dtype=int64)
tf.Tensor([2 2 0 0], shape=(4,), dtype=int64)
