In [2]:
import tensorflow as tf
a=tf.constant([1,2,3,1,1])
b=tf.constant([0,1,3,4,5])
c=tf.where(tf.greater(a,b), a, b) #若a>b，返回a对应位置的元素，否则 返回b对应位置的元素
print("c:",c)

c: tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [3]:
import numpy as np
rdm=np.random.RandomState(seed=1) #seed=常数每次生成随机数相同 a=rdm.rand() # 返回一个随机标量
b=rdm.rand(2,3) #返回维度为2行3列随机数矩阵
print("a:",a)
print("b:",b)

a: tf.Tensor([1 2 3 1 1], shape=(5,), dtype=int32)
b: [[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]]


In [4]:
import numpy as np 
a = np.array([1,2,3]) 
b = np.array([4,5,6]) 
c = np.vstack((a,b)) 
print("c:\n",c)

c:
 [[1 2 3]
 [4 5 6]]


In [5]:
import numpy as np
x, y = np.mgrid [1:3:1, 2:4:0.5] 
grid = np.c_[x.ravel(), y.ravel()] 
print("x:",x)
print("y:",y)
print('grid:\n', grid)

x: [[1. 1. 1. 1.]
 [2. 2. 2. 2.]]
y: [[2.  2.5 3.  3.5]
 [2.  2.5 3.  3.5]]
grid:
 [[1.  2. ]
 [1.  2.5]
 [1.  3. ]
 [1.  3.5]
 [2.  2. ]
 [2.  2.5]
 [2.  3. ]
 [2.  3.5]]
